---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nas-creds
  namespace: cilium
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: nas-creds
  data:
  - secretKey: nas-sshkey
    remoteRef:
      key: /nas01-creds
      property: sshkey
      decodingStrategy: Base64
  - secretKey: nas-username
    remoteRef:
      key: /nas01-creds
      property: username
  - secretKey: nas-host
    remoteRef:
      key: /nas01-creds
      property: host