---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble
  namespace: cilium
spec:
  parentRefs:
  - name: tls
    namespace: cilium
    sectionName: https
  hostnames: 
  - hubble.ucdialplans.com
  rules:
  - backendRefs:
    - name: hubble-ui
      namespace: cilium
      kind: Service
      port: 80