apiVersion: v1
kind: ConfigMap
metadata:
  name: env-vars
  namespace: pocket-id
data:
  APP_URL: "https://pocket-id.ucdialplans.com"
  TRUST_PROXY: "true"
  PUID: "1000"
  PGID: "0"
  DB_PROVIDER: "postgres"
  FILE_BACKEND: "database"
  KEYS_STORAGE: "database"