apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../../../helm
helmCharts:
- name: baseline
  releaseName: pocket-id
  namespace: pocket-id
  valuesFile: values.yaml
resources:
- env-vars.yaml
- database.yaml
- external-secrets.yaml
- namespace.yaml
