image:
  repository: phueber/prefetcharr
  tag: latest
  registry: docker.io
  imagePullPolicy: Always
  env:
  - name: PREFETCHARR_CONFIG
    value: "default"
# securityContext:
#   allowPrivilegeEscalation: false
#   readOnlyRootFilesystem: true
#   runAsNonRoot: true
#   runAsUser: 1000
#   runAsGroup: 0
#   seccompProfile:
#     type: RuntimeDefault
#   capabilities:
#     drop: ["ALL"]
# resources:
#   requests:
#     cpu: 2m
#     memory: 160Mi
#   limits:
#     # cpu: 500m
#     memory: 300Mi
# livenessProbe:
#   httpGet:
#     path: /ping
#     port: http
#   initialDelaySeconds: 20
#   timeoutSeconds: 5
#   periodSeconds: 10
#   successThreshold: 1
#   failureThreshold: 10
extraVolumes:
- name: prefetcharr-config
  secret:
    secretName: prefetcharr-config
    items:
      - key: config
        path: config
extraVolumeMounts:
- name: prefetcharr-config
  mountPath: /config
  subPath: config