apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: tautulli
  namespace: media
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: tautulli
  ingress:
    - fromEntities:
        - ingress
        - remote-node
      toPorts:
        - ports:
            - port: "8181"
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: maintainerr
        - matchLabels:
            app.kubernetes.io/name: prefetcharr
        - matchLabels:
            app.kubernetes.io/name: seerr
      toPorts:
        - ports:
            - port: "8181"
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: plex
      toPorts:
        - ports:
            - port: "32400"
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: seerr
      toPorts:
        - ports:
            - port: "5055"
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
