apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: volsync
helmCharts:
- name: volsync
  repo: https://backube.github.io/helm-charts
  version: 0.14.0
  releaseName: volsync
  namespace: volsync
  valuesFile: ../../base/values.yaml
resources:
- ../../base
# These CRDs are necessary for Volsync to work even though we are not using VolumeSnapshots directly.
- github.com/kubernetes-csi/external-snapshotter/client/config/crd?ref=v8.4.0
