apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: pgadmin4
  repo: https://helm.runix.net/
  version: 1.50.0
  releaseName: pgadmin
  namespace: cnpg
  valuesFile: values.yaml
resources:
- backup.yaml
- database.yaml
- external-secrets.yaml
- httproute.yaml
- volume.yaml