image:
  repository: dpage/pgadmin4
  tag: 9.9.0
  registry: docker.io
containerSecurityContext:
  enabled: true
  allowPrivilegeEscalation: false
existingSecret: postgresql-passwords
secretKeys:
  pgadminPasswordKey: postgresql-admin-pw
env:
  email: ken.lasko@gmail.com
serverDefinitions:
  enabled: true
  servers:
    firstServer: 
      Name: "Home"
      Group: "Servers"
      Port: 5432
      Username: postgres
      Host: home-rw.cnpg.svc.cluster.local
      MaintenanceDB: "postgres"
persistentVolume:
  enabled: true
  accessModes:
  - ReadWriteOnce
  size: 12Gi
  storageClassName: "nfs"
  existingClaim: nfs-pgadmin
containerSecurityContext:
  enabled: true
  allowPrivilegeEscalation: false
resources:
  requests:
    cpu: 1m
    memory: 175Mi
  limits:
    memory: 4Gi