image:
  repository: 11notes/prowlarr
  tag: 2.3.0
  registry: ghcr.io
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 0
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
resources:
  requests:
    cpu: 2m
    memory: 160Mi
  limits:
    # cpu: 500m
    memory: 300Mi
service:
  port: 9696
livenessProbe:
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 20
  timeoutSeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 10
media:
  enabled: true
persistentVolume:
  type: nfs
  size: 600Mi
  mountPath: /prowlarr/etc
extraVolumes:
- name: tmpfs
  emptyDir:
    medium: Memory
extraVolumeMounts:
- name: tmpfs
  mountPath: /tmp
backup:
  location: cloudflare
  schedule: "55 06 * * *"
oidc:
  enabled: true
  secretName: env-secrets-prowlarr