apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../../../helm
helmCharts:
- name: baseline
  releaseName: maintainerr
  namespace: media
  valuesFile: values.yaml
resources:
- external-secrets.yaml
# - networkpolicy.yaml