image:
  repository: maintainerr/maintainerr
  tag: 2.20.0
  registry: ghcr.io
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 100
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
resources:
  requests:
    cpu: 1m
    memory: 170Mi
  limits:
    # cpu: 500m
    memory: 600Mi
service:
  port: 6246
media:
  enabled: true
persistentVolume:
  type: longhorn
  size: 8Gi
  mountPath: /opt/data