image:
  repository: maintainerr/maintainerr
  tag: 2.22.1
  registry: ghcr.io
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 0
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
resources:
  requests:
    cpu: 1m
    memory: 170Mi
  limits:
    # cpu: 500m
    memory: 800Mi
service:
  port: 6246
media:
  enabled: true
persistentVolume:
  type: longhorn
  size: 8Gi
  mountPath: /opt/data