# This file overrides some ArgoCD ApplicationSet parameters. It does not have to be populated, but it must exist.
autoSync: true
info:
- name: "Website:"
  value: "https://cert-manager.io/"
- name: "Documentation:"
  value: "https://cert-manager.io/docs/"
- name: "Repository:"
  value: "https://github.com/cert-manager/cert-manager"