# This file overrides some ArgoCD ApplicationSet parameters. It does not have to be populated, but it must exist.
autoSync: true
info:
- name: "Documentation:"
  value: "https://github.com/kubernetes-sigs/descheduler/blob/master/docs/user-guide.md"
- name: "Repository:"
  value: "https://github.com/kubernetes-sigs/descheduler"