---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: portainer
  namespace: portainer
spec:
  trigger:
    manual: restore-once
  restic:
    repository: s3-backup-cloudflare-portainer
    destinationPVC: nfs-portainer
    copyMethod: Direct
    enableFileDeletion: true
    cleanupTempPVC: true
    cleanupCachePVC: true
    storageClassName: nfs-csi
    cacheStorageClassName: nfs-csi-dynamic-backup
    # restoreAsOf: "2025-03-05T06:50:00Z"
    # previous: 3   # Number of backup items to skip backwards. Can be used instead of restoreAsOf.
    moverSecurityContext:
      runAsNonRoot: false
      runAsUser: 0
      runAsGroup: 100
      seccompProfile:
        type: RuntimeDefault