---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: env-secrets
  namespace: pocket-id
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: env-secrets
  dataFrom:
  - extract:
      key: /pocket-id


---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-connection-string
  namespace: pocket-id
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: db-connection-string
    template:
      engineVersion: v2
      data:
        DB_CONNECTION_STRING: "postgres://{{ .dbUsername }}:{{ .dbPassword }}@home-rw.cnpg.svc.cluster.local:5432/pocket-id"
  data:
  - secretKey: dbUsername
    remoteRef:
      key: /database/pocket-id
      property: username
  - secretKey: dbPassword
    remoteRef:
      key: /database/pocket-id
      property: password
