apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../../../helm
helmCharts:
- name: baseline
  releaseName: it-tools
  namespace: it-tools
  valuesFile: values.yaml
resources:
- namespace.yaml
