image:
  repository: sharevb/it-tools
  tag: 2026.1.4
  registry: ghcr.io
priorityClassName: low-priority
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  seccompProfile:
    type: RuntimeDefault
  # capabilities:
  #   drop: ["ALL"]
resources:
  requests:
    cpu: 1m
    memory: 10Mi
  limits:
    # cpu: 200m
    memory: 50Mi
service:
  port: 8080