# This file overrides some ArgoCD ApplicationSet parameters. It does not have to be populated, but it must exist.
autoSync: true
info:
- name: "Website:"
  value: "https://moneymate.io/"
- name: "Documentation:"
  value: "https://docs.moneymate.io/"
- name: "Repository:"
  value: "https://github.com/moneymate-recipes/moneymate/"