image:
  repository: sctx/overseerr
  tag: develop
  registry: docker.io
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
resources:
  requests:
    cpu: 3m
    memory: 220Mi
  limits:
    # cpu: 1000m
    memory: 800Mi
service:
  port: 5055
extraHTTPRouteHostnames:
- media.ucdialplans.com
persistentVolume:
  type: longhorn
  size: 250Mi
  mountPath: /app/config