apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale
helmCharts:
- name: tailscale-operator
  repo: https://pkgs.tailscale.com/helmcharts/
  version: 1.92.4
  releaseName: tailscale-operator
  namespace: tailscale
  valuesFile: ../../base/values.yaml
  additionalValuesFiles:
  - values.yaml
  valuesMerge: merge
resources:
- ../../base
- proxyclass.yaml