apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-env
  namespace: monitoring
data:
  GF_ANALYTICS_REPORTING_ENABLED: "false"
  GF_ANALYTICS_CHECK_FOR_UPDATES: "false"
  GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES: "false"
  GF_SERVER_ROOT_URL: "https://grafana.ucdialplans.com/"
  GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
  GF_AUTH_BASIC_ENABLED: "false"
  GF_AUTH_DISABLE_LOGIN_FORM: "false"
  GF_AUTH_GENERIC_OAUTH_NAME: "Pocket ID"
  GF_DATABASE_TYPE: "postgres"
  GF_DATABASE_HOST: "home-rw.cnpg.svc.cluster.local:5432"
  GF_DATABASE_NAME: "grafana"