---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-env-secrets
  namespace: monitoring
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: grafana-env-secrets
  data:
  - secretKey: GF_DATABASE_USER
    remoteRef:
      key: /database/grafana
      property: username
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: GF_DATABASE_PASSWORD
    remoteRef:
      key: /database/grafana
      property: password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  dataFrom:
  - extract:
      key: /grafana
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None