# Notification level (debug, info, success, warn, error, fatal)
notificationLevel: debug
debug: true

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: DoesNotExist
        - key: kubernetes.io/arch
          operator: In
          values: 
          - 'amd64'

polling:
  enabled: false
  defaultSchedule: "@every 2h"

helmProvider:
  enabled: false

secret:
  name: keel-creds
  create: false

mail:
  enabled: false
  from: "Keel Updates <keelupdates@ucdialplans.com>"
  to: "ken.lasko@gmail.com"
  smtp:
    server: "smtp.sendgrid.net"
    port: 587
    user: "apikey"

basicauth:
  enabled: true
  user: "kenadmin"

persistence:
  enabled: true
  storageClass: nfs-csi
  size: 5Mi

service:
  enabled: true
  type: ClusterIP
  
serviceAnnotations:
  omni-kube-service-exposer.sidero.dev/port: "50105"
  omni-kube-service-exposer.sidero.dev/label: Keel
  omni-kube-service-exposer.sidero.dev/icon: |
    H4sICE0LJ2YAA2suc3ZnAEWQ0W6DMAxF3/cVVvZs4yQkJBPwsD+hXdZUC1AVRvr5C0XqpCtdH+va
    ltwu2wUeY5qWTsR1vX1UVc6Zsqb5fqkUM1clIWC7hvw5PzrBwGDrIgFhGk4p4Gk4/1zu8+/01Ykp
    ZPhP9O1tWCOU/qgVqDNKS8Y6YNQMUlOt1V5pXg6AJxzCVwtfgAdoHi2xtFDXZNgldOS1R6nIWouK
    vCrHyFu5eWrYRDQF9IbK71PxICnJG5OKKSnxoNiQ0zY9iT3spmsoe410IBtipyI21Hgj4PuaUife
    ZXAuGFH17f6n/u0PkrcaBlABAAA=

resources:
  requests:
    cpu: 6m
    memory: 52Mi
  limits:
    cpu: 100m
    memory: 70Mi