---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: env-secrets-homeassist
  namespace: homeops
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: env-secrets-homeassist
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Merge # CRITICAL: This allows the 'dataFrom' keys to exist alongside the template data
      data:
        DATABASE_URL: "postgres://{{ .db_user }}:{{ .db_pass }}@home-rw.cnpg.svc.cluster.local:5432/{{ .db_user }}"
  data:
  # Database creds for template
  - secretKey: db_user
    remoteRef:
      key: /database/homeassist
      property: username
  - secretKey: db_pass
    remoteRef:
      key: /database/homeassist
      property: password
  # Pull all other KV pairs from /homeassist
  dataFrom:
  - extract:
      key: /homeassistant/env-vars

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-deploy-key
  namespace: homeops
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: github-deploy-key
  data:
  - secretKey: privateKey
    remoteRef:
      key: /github/homeassistant-deploy-key

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kube-auth-token
  namespace: homeops
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: kube-auth-token
  dataFrom:
  - extract:
      key: /homeassistant/kube-auth-token

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp2go-credentials
  namespace: homeops
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: smtp2go-credentials
  dataFrom:
  - extract:
      key: /alertmanager
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  data:
  - secretKey: SMTP2GO_USERNAME
    remoteRef:
      key: /email/smtp2go
      property: username
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: SMTP2GO_PW
    remoteRef:
      key: /email/smtp2go
      property: password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None