apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../../../helm
helmCharts:
- name: baseline
  releaseName: homeassist
  namespace: homeops
  valuesFile: values.yaml
resources:
- database.yaml
- external-secrets.yaml
- namespace.yaml
#- networkpolicy.yaml
- serviceaccount.yaml
