apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: homeassist
  namespace: homeops
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: homeassist
  ingress:
    - fromEntities:
        - ingress
        - remote-node
      toPorts:
        - ports:
            - port: "8123"
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: cloudflare-tunnel
            k8s:io.kubernetes.pod.namespace: cloudflare
      toPorts:
        - ports:
            - port: "8123"
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: pangolin-tunnel
            k8s:io.kubernetes.pod.namespace: pangolin
      toPorts:
        - ports:
            - port: "8123"
    - fromEndpoints:
        - {}
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: prometheus
            k8s:io.kubernetes.pod.namespace: monitoring
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: dawarich
            k8s:io.kubernetes.pod.namespace: dawarich
      toPorts:
        - ports:
            - port: "3000"
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: adguard
            k8s:io.kubernetes.pod.namespace: adguard
      toPorts:
        - ports:
            - port: "3000"
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: dead-man-hand
            k8s:io.kubernetes.pod.namespace: dmh
      toPorts:
        - ports:
            - port: "8080"
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: plex
            k8s:io.kubernetes.pod.namespace: media
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: uptime-kuma
            k8s:io.kubernetes.pod.namespace: uptime-kuma
      toPorts:
        - ports:
            - port: "80"
    - toFQDNs:
      - matchName: mail.smtp2go.com
      toPorts:
      - ports:
        - port: "587"
          protocol: TCP
    - toEndpoints:
        - {}
    - toEntities:
        - world
