image:
  repository: home-assistant/home-assistant
  tag: 2025.12.1
  registry: ghcr.io
priorityClassName: high-priority
hostNetwork: true
serviceAccountName: ha-sa-garminupload
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
env:
- name: PYTHONPATH
  value: "/config/deps/"
- name: TZ
  value: "America/Toronto"
envFrom:
- secretRef:
    name: kube-auth-token
- secretRef:
    name: env-secrets-homeassist
- secretRef:
    name: smtp2go-credentials
resources:
  requests:
    cpu: 100m
    memory: 700Mi
    smarter-devices/ttyUSB1: 1
  limits:
    # cpu: 1400m
    memory: 1300Mi
    smarter-devices/ttyUSB1: 1
service:
  port: 8123
livenessProbe:
  httpGet:
    path: /manifest.json
    port: http
  initialDelaySeconds: 30
  periodSeconds: 60
  timeoutSeconds: 5
httpRouteNameOverride: "ha.ucdialplans.com"
persistentVolume:
  type: nfs
  size: 4Gi
extraVolumes:
- name: github-deploy-key
  secret:
    secretName: github-deploy-key
    defaultMode: 0400
- name: tmp
  emptyDir: {}
extraVolumeMounts:
- name: github-deploy-key
  mountPath: /config/.ssh/id_ed25519
  subPath: privateKey
  readOnly: true
- name: tmp
  mountPath: /tmp
backup:
  location: cloudflare 
  copyMethod: Direct
  schedule: "00 */2 * * *"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nuc4