apiVersion: v1
kind: Service
metadata:
  labels:
    app: overseerr-service
  name: overseerr-service
  namespace: media-tools
spec:
  type: ClusterIP
  ports:
  - port: 5055
    protocol: TCP
    targetPort: http
    name: web
  selector:
    app: overseerr