image:
  repository: instantlinux/nut-upsd
  tag: 2.8.3-r2
  registry: docker.io
priorityClassName: high-priority
disableHTTPRoute: true
securityContext:
  privileged: true
  seccompProfile:
    type: RuntimeDefault
env:
- name: NUT_DEBUG_LEVEL
  value: "1"
- name: TZ
  value: "America/Toronto"
envFrom:
- secretRef:
    name: ups-creds
resources:
  requests:
    cpu: 1m
    memory: 3Mi
    # smarter-devices/hidraw0: 1
    smarter-devices/bus_usb_001_002: 1
    smarter-devices/bus_usb_001_004: 1
  limits:
    # cpu: 1m
    memory: 5Mi
    # smarter-devices/hidraw0: 1
    smarter-devices/bus_usb_001_002: 1
    smarter-devices/bus_usb_001_004: 1
service:
  port: 3493
livenessProbe: 
  tcpSocket: 
    port: 3493 
  initialDelaySeconds: 15
  periodSeconds: 60
persistentVolume:
  type: nfs
  size: 10Mi
  mountPath: /etc/nut
backup:
  location: cloudflare
  schedule: "30 6 * * *"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nuc4