# This file overrides some ArgoCD ApplicationSet parameters. It does not have to be populated, but it must exist.
autoSync: true
info:
- name: "Documentation:"
  value: "https://grafana.com/docs/alloy/latest/"
- name: "Repository:"
  value: "https://github.com/grafana/alloy"