apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: authentik
  repo: https://charts.goauthentik.io
  version: 2025.10.1
  releaseName: authentik
  namespace: authentik
  valuesFile: ../../base/values.yaml
resources:
- ../../base
- database.yaml
# - external-secrets.yaml
# - httproute.yaml
# - volume.yaml