# This file overrides some ArgoCD ApplicationSet parameters. It does not have to be populated, but it must exist.
autoSync: true
info:
- name: "Website:"
  value: "https://uptimekuma.org/"
- name: "Documentation:"
  value: "https://uptimekuma.org/wiki/"
- name: "Repository:"
  value: "https://github.com/louislam/uptime-kuma"