---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: env-secrets-nttdemo
  namespace: nectar-mcp
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: env-secrets-nttdemo
  dataFrom:
  - extract:
      key: /nectar/nttdemo