apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../../../helm
helmCharts:
- name: baseline
  releaseName: nectar-mcp
  namespace: nectar-mcp
  valuesFile: values.yaml
resources:
- env-vars.yaml
- external-secrets.yaml
