apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis
helmGlobals:
  chartHome: ../../../../../helm
helmCharts:
- name: baseline
  releaseName: redis-insight
  namespace: redis
  valuesFile: ../../base/values.yaml
  additionalValuesFiles:
  - values.yaml
  valuesMerge: merge
resources:
- ../../base