apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ha-accessrole-garminupload
  namespace: garmin-upload
rules:
- apiGroups:
  - batch
  resources: ["*"]
  # - cronjobs
  # - jobs
  verbs: ["get", "delete", "create"]