apiVersion: v1
kind: Service
metadata:
  labels:
    app: radarr-service
  name: radarr-service
  namespace: media-tools
spec:
  type: ClusterIP
  ports:
  - port: 7878
    protocol: TCP
    targetPort: http
    name: web
  selector:
    app: radarr