# This volume is for access to all the NAS-based media files
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  storageClassName: nfs-csi
  capacity:
    storage: 20Ti
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 192.168.1.3/media
    volumeAttributes:
      server: 192.168.1.3
      share: /media

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media
  namespace: media
spec:
  storageClassName: nfs-csi
  volumeName: nfs-media
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Ti

# This volume is for granting access to the media downloads folder
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-downloads
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  storageClassName: nfs-csi
  capacity:
    storage: 2Ti
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 192.168.1.3/media/downloads
    volumeAttributes:
      server: 192.168.1.3
      share: /media/downloads

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-downloads
  namespace: media
spec:
  storageClassName: nfs-csi
  volumeName: nfs-media-downloads
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Ti


# This volume is for application backups
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-app-backup
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  storageClassName: nfs-csi
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 192.168.1.3/backup/media-apps
    volumeAttributes:
      server: 192.168.1.3
      share: /backup/media-apps

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-app-backup
  namespace: media
spec:
  storageClassName: nfs-csi
  volumeName: nfs-media-app-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi