apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: intel-device-plugins-gpu
  repo: https://intel.github.io/helm-charts/
  version: 0.35.0
  releaseName: intel-device-plugins-gpu
  namespace: intel-gpu
  includeCRDs: true
  valuesFile: values-gpu.yaml
- name: intel-device-plugins-operator
  repo: https://intel.github.io/helm-charts/
  version: 0.34.1
  releaseName: intel-device-plugins-operator
  namespace: intel-gpu
  includeCRDs: true
  valuesFile: values-operator.yaml
resources:
- namespace.yaml

