# This file overrides some ArgoCD ApplicationSet parameters. It does not have to be populated, but it must exist.
info:
- name: "Documentation:"
  value: "https://dispatcharr.github.io/Dispatcharr-Docs/"
- name: "Repository:"
  value: "https://github.com/Dispatcharr/Dispatcharr"