image:
  repository: oracle/oci-cli
  tag: "20251029"
  registry: ghcr.io
priorityClassName: low-priority
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
# resources:
#   requests:
#     cpu: 1m
#     memory: 7Mi
#   limits:
#     # cpu: 250m
#     memory: 30Mi
command: ["bash","-c","sleep 99d"]
env:
- name: OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING
  value: "True"
disableHTTPRoute: true
extraVolumes:
- name: oci-config-file
  secret:
    secretName: oci-config-file
- name: oci-private-key
  secret:
    secretName: oci-private-key
- configMap:
    items:
    - key: update-security-rule.sh
      path: update-security-rule.sh
    defaultMode: 0755
    name: update-security-rule
  name: update-security-rule
extraVolumeMounts:
- name: oci-config-file
  mountPath: /oracle/.oci
  readOnly: true
- name: oci-private-key
  mountPath: /certs
  readOnly: true
- name: update-security-rule
  mountPath: /scripts/update-security-rule.sh
  subPath: update-security-rule.sh
  readOnly: true
  

