anonymousUserEnabled: false
debug: false
db:
  type: postgres
secret:
  create: false
  existingSecret: kite-secrets
extraEnvs:
- name: "HOST"
  value: "https://kite.ucdialplans.com"
- name: "NODE_TERMINAL_IMAGE"
  value: "nicolaka/netshoot"
