# This file overrides some ArgoCD ApplicationSet parameters. It does not have to be populated, but it must exist.
autoSync: true
syncWave: "0"
info:
- name: "Documentation:"
  value: "https://pocket-id.org/docs"
- name: "Repository:"
  value: "https://github.com/pocket-id/pocket-id"