---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-secrets
  namespace: mealie
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: mealie-secrets
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: /database/mealie
      property: username
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: /database/mealie
      property: password