apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../../../helm
helmCharts:
- name: baseline
  releaseName: mealie
  namespace: mealie
  valuesFile: values.yaml
resources:
- database.yaml
- env-vars.yaml
- external-secrets.yaml
- namespace.yaml
