image:
  repository: mealie-recipes/mealie
  tag: v3.9.2
  registry: ghcr.io
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 0
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
env:
- name: ALLOW_SIGNUP
  value: "false"
- name: BASE_URL
  value: "https://mealie.ucdialplans.com"
- name: PUID
  value: "1000"
- name: PGID
  value: "0"           
- name: TZ
  value: "America/Toronto"
- name: DB_ENGINE
  value: "postgres"
- name: POSTGRES_SERVER
  value: "home-rw.cnpg.svc.cluster.local"
- name: POSTGRES_DB
  value: "mealie"
envFrom:
- secretRef:
    name: mealie-secrets
resources:
  requests:
    cpu: 100m
    memory: 300Mi
  limits:
    memory: 500Mi
service:
  port: 9000
extraHTTPRouteHostnames:
- recipes.ucdialplans.com
persistentVolume:
  type: nfs
  size: 450Mi
  mountPath: /app/data
backup:
  location: cloudflare 
  schedule: "20 7 * * *"
