apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: standby
  namespace: cnpg
spec:
  # Use ghcr.io/cloudnative-pg/postgresql:17.6-standard-trixie for basic usage
  # Use ghcr.io/tensorchord/cloudnative-vectorchord:17.6-0.3.0 for vchord (Immich)
  # Use kenlasko/cloudnativepg-gis-vchord:17.6-vc0.4.2-1 for vchord (Immich) and GIS (Dawarich)
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6-minimal-trixie
  instances: 1

  # Bootstrap from the main home 3-node cluster
  bootstrap:
    # Boostrap from main cluster for speed
    # pg_basebackup:
    #   source: home-postgresql
    # Bootstrap from S3 backup to test restore procedures (normally disabled)
    recovery:
      source: s3-backupsource
  replica:
    enabled: true
    source: home-postgresql 

  storage:
    storageClass: local-storage
    size: 14Gi
  resources:
    requests:
      cpu: 10m
      memory: 250Mi
    limits:
      memory: 1Gi
  enableSuperuserAccess: true
  superuserSecret:
    name: postgresql-superuser


  externalClusters:
  - name: home-postgresql
    connectionParameters:
      host: home-r
      user: streaming_replica
      sslmode: verify-full
      dbname: postgres
    sslKey:
      name: home-replication
      key: tls.key
    sslCert:
      name: home-replication
      key: tls.crt
    sslRootCert:
      name: home-ca
      key: ca.crt
  - name: s3-backupsource
    plugin:
      name: barman-cloud.cloudnative-pg.io
      enabled: true
      isWALArchiver: false
      parameters:
        barmanObjectName: backblaze
        serverName: home

  postgresql:
    shared_preload_libraries: []
    parameters:
      max_connections: "200"