apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    cnpg.io/cluster: home
  name: home
  namespace: cnpg
spec:
  namespaceSelector:
    matchNames:
    - cnpg
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels:
      cnpg.io/cluster: home
      cnpg.io/podRole: instance
