apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: podmonitor-home
  namespace: cnpg
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: home
  podMetricsEndpoints:
  - port: metrics
    scheme: https
    tlsConfig:
      ca:
        secret:
          name: home-ca
          key: ca.crt
      serverName: home-rw
    bearerTokenSecret:
      key: ''
      name: ''
    relabelings:
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
      action: replace