# Provides access to KubeAPI via load balancer instead of directly through node or via Omni
# Useful in case of issues with Omni


# This option doesn't work yet, because Cilium doesn't support BackendTLSPolicy yet
# See https://github.com/cilium/cilium/issues/31352

# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: kubeapi
#   namespace: default
# spec:
#   parentRefs:
#   - name: kubeapi
#     namespace: cilium
#     sectionName: https
#   hostnames:
#   - "kube.ucdialplans.com"
#   rules:
#   - backendRefs:
#     - name: kubernetes
#       namespace: default
#       group: ""
#       kind: Service
#       port: 443

# ---
# apiVersion: gateway.networking.k8s.io/v1alpha2
# kind: BackendTLSPolicy
# metadata:
#   name: kube-tls-policy
#   namespace: default
# spec:
#   targetRef:
#     kind: Service
#     name: kubernetes
#     group: ""
#     namespace: default
#   tls:
#     caCertRefs: 
#       - kind: ConfigMapReference
#         name: kube-root-ca.crt
#         group: ""
#     hostname: kube.ucdialplans.com



---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: kubeapi
  namespace: default
spec:
  parentRefs:
  - name: kubeapi
    namespace: cilium
    sectionName: https
  hostnames:
  - "kube.ucdialplans.com"
  rules:
  - backendRefs:
    - name: kubernetes
      namespace: default
      kind: Service
      port: 443