---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-db-credentials
  namespace: nextcloud
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: nextcloud-db-credentials
  dataFrom:
  - extract:
      key: /database/nextcloud

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        nextcloud-username: "{{ .nextcloudUsername }}"
        nextcloud-password: "{{ .nextcloudPassword }}"
        smtp-username: "{{ .smtpUsername }}"
        smtp-password: "{{ .smtpPassword }}"
        smtp-host: "mail.smtp2go.com"
        redis-password: "{{ .redisPassword }}"
  data:
  - secretKey: nextcloudUsername
    remoteRef:
      key: /nextcloud
      property: nextcloud-username
  - secretKey: nextcloudPassword
    remoteRef:
      key: /nextcloud
      property: nextcloud-password
  - secretKey: smtpUsername
    remoteRef:
      key: /email/smtp2go
      property: username
  - secretKey: smtpPassword
    remoteRef:
      key: /email/smtp2go
      property: password
  - secretKey: redisPassword
    remoteRef:
      key: /redis
      property: RI_REDIS_PASSWORD

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-backup-cloudflare-nextcloud
  namespace: nextcloud
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .awsAccessKeyID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .awsSecretAccessKey }}"
        RESTIC_PASSWORD: "{{ .resticPassword }}"
        RESTIC_REPOSITORY: "{{ .resticRepository }}/nextcloud"
  data:
  - secretKey: awsAccessKeyID
    remoteRef:
      key: /s3/cloudflare
      property: AWS_ACCESS_KEY_ID
  - secretKey: awsSecretAccessKey
    remoteRef:
      key: /s3/cloudflare
      property: AWS_SECRET_ACCESS_KEY
  - secretKey: resticRepository
    remoteRef:
      key: /s3/cloudflare
      property: RESTIC_REPOSITORY
  - secretKey: resticPassword
    remoteRef:
      key: /s3/cloudflare
      property: RESTIC_PASSWORD

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-backup-backblaze-nextcloud
  namespace: nextcloud
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .awsAccessKeyID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .awsSecretAccessKey }}"
        RESTIC_PASSWORD: "{{ .resticPassword }}"
        RESTIC_REPOSITORY: "{{ .resticRepository }}"
  data:
  - secretKey: awsAccessKeyID
    remoteRef:
      key: /s3/backblaze
      property: AWS_ACCESS_KEY_ID
  - secretKey: awsSecretAccessKey
    remoteRef:
      key: /s3/backblaze
      property: AWS_SECRET_ACCESS_KEY
  - secretKey: resticRepository
    remoteRef:
      key: /s3/backblaze
      property: RESTIC_REPOSITORY_NEXTCLOUD
  - secretKey: resticPassword
    remoteRef:
      key: /s3/backblaze
      property: RESTIC_PASSWORD