internalDatabase:
  enabled: false
externalDatabase:
  enabled: true
  type: postgresql
  host: home-rw.cnpg.svc.cluster.local
  secretName: nextcloud-db-credentials
  usernameKey: username
  passwordKey: password
cronjob:
  enabled: true
resources:
  requests:
    cpu: 20m
    memory: 150Mi
  limits:
    memory: 4Gi

nextcloud:
  host: nextcloud.ucdialplans.com
  trustedDomains:
  - ucdialplans.com
  - nextcloud.ucdialplans.com
  # podSecurityContext:
  #   runAsUser: 33
  #   runAsGroup: 33
  #   runAsNonRoot: false
  #   readOnlyRootFilesystem: false
  existingSecret:
    enabled: true
    secretName: nextcloud-secrets
    usernameKey: nextcloud-username
    passwordKey: nextcloud-password
    tokenKey: ""
    smtpUsernameKey: smtp-username
    smtpPasswordKey: smtp-password
    smtpHostKey: smtp-host
  extraEnv:
  - name: OVERWRITEPROTOCOL
    value: https
  - name: OVERWRITECLIURL
    value: https://nextcloud.ucdialplans.com
  - name: REDIS_HOST
    value: redis-service.redis.svc.cluster.local
  - name: REDIS_HOST_PASSWORD
    valueFrom:
      secretKeyRef:
        name: nextcloud-secrets
        key: redis-password
  mail:
    enabled: true
    fromAddress: nextcloud
    domain: ucdialplans.com
    smtp:
      host: mail.smtp2go.com
      secure: starttls
      port: 587
      authtype: LOGIN

collabora:
  enabled: true
  collabora:
    aliasgroups:
    - host: "https://nextcloud.ucdialplans.com"
    existingSecret:
      enabled: true
      secretName: nextcloud-secrets
      usernameKey: nextcloud-username
      passwordKey: nextcloud-password
    extra_params: >-
      --o:ssl.enable=false 
      --o:ssl.termination=true
  resources:
    requests:
      cpu: 2m
      memory: 470Mi
    limits:
      memory: 750Mi

deploymentLabels:
  cnpg-client: "true"

persistence:
  enabled: true
  existingClaim: nfs-nextcloud-config
  nextcloudData:
    enabled: true
    existingClaim: nfs-nextcloud-data
    accessMode: ReadWriteOnce
    size: 500Gi

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false