apiVersion: v1
kind: ConfigMap
metadata:
  name: seerr-env
  namespace: media
data:
  DB_TYPE: "postgres"
  DB_HOST: "home-rw.cnpg.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "seerr"
  TZ: "America/Toronto"