---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-secrets
  namespace: media
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: seerr-secrets
  data:
  - secretKey: DB_USER
    remoteRef:
      key: /database/seerr
      property: username
  - secretKey: DB_PASS
    remoteRef:
      key: /database/seerr
      property: password