image:
  repository: fallenbagel/jellyseerr #seerr-team/seerr
  tag: 2.7.3
  registry: ghcr.io
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
envFrom:
- configMapRef:
    name: seerr-env
- secretRef:
    name: seerr-secrets
resources:
  requests:
    cpu: 3m
    memory: 220Mi
  limits:
    # cpu: 1000m
    memory: 700Mi
service:
  port: 5055
livenessProbe: "false"
extraHTTPRouteHostnames:
- media.ucdialplans.com
- overseerr.ucdialplans.com
persistentVolume:
  type: nfs
  size: 650Mi
  mountPath: /app/config
backup:
  location: cloudflare
  schedule: "15 07 * * *"
