image:
  repository: ersatztv/ersatztv
  tag: v25.8.0
  registry: ghcr.io
securityContext:
  # allowPrivilegeEscalation: false
  # readOnlyRootFilesystem: false
  # runAsNonRoot: true
  runAsUser: 0
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
resources:
  requests:
    cpu: 100m
    memory: 650Mi
    gpu.intel.com/i915: "1"
  limits:
    # cpu: 1000m
    memory: 1.5Gi 
    gpu.intel.com/i915: "1"
service:
  port: 8409 
persistentVolume:
  type: nfs
  size: 700Mi
media:
  enabled: true
backup:
  location: cloudflare
  schedule: "40 06 * * *"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: intel.feature.node.kubernetes.io/gpu
          operator: In
          values:
          - "true"
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nuc5
          - nuc6