# This file overrides some ArgoCD ApplicationSet parameters. It does not have to be populated, but it must exist.
autoSync: true
info:
- name: "Website/Documentation:"
  value: "https://docs.stakater.com/reloader/"
- name: "Repository:"
  value: "https://github.com/stakater/Reloader"