apiVersion: v1
kind: ConfigMap
metadata:
  name: env-vars-backend
  namespace: monize
data:
  NODE_ENV: "production"
  DATABASE_HOST: "home-rw.cnpg.svc.cluster.local"
  DATABASE_NAME: monize
  PUBLIC_APP_URL: https://monize.ucdialplans.com
  OIDC_ISSUER_URL: https://auth.ucdialplans.com
  OIDC_CALLBACK_URL: https://monize.ucdialplans.com/api/v1/auth/oidc/callback
  LOCAL_AUTH_ENABLED: "false"
  REGISTRATION_ENABLED: "false"
  SMTP_HOST: "mail.smtp2go.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"  # Not required for STARTTLS
  EMAIL_FROM: "monize@ucdialplans.com"
  AI_DEFAULT_PROVIDER: ollama
  AI_DEFAULT_MODEL: llama3
  AI_DEFAULT_BASE_URL: http://ollama.ollama.svc.cluster.local:11434


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-vars-frontend
  namespace: monize
data:
  NODE_ENV: "production"
  INTERNAL_API_URL: http://monize-backend-service:3001
  PUBLIC_APP_URL: https://monize.ucdialplans.com
