apiVersion: v1
kind: Service
metadata:
  labels:
    app: readarr-service
  name: readarr-service
  namespace: media-tools
spec:
  type: ClusterIP
  ports:
  - port: 8787
    protocol: TCP
    targetPort: http
    name: web
  selector:
    app: readarr