# This file overrides some ArgoCD ApplicationSet parameters. It does not have to be populated, but it must exist.
autoSync: true
info:
- name: "Website:"
  value: "https://maintainerr.info/"
- name: "Documentation:"
  value: "https://docs.maintainerr.info/latest/"
- name: "Repository:"
  value: "https://github.com/jorenn92/Maintainerr"