apiVersion: v1
kind: Service
metadata:
  labels:
    app: owntracks-recorder
  name: owntracks-recorder
  namespace: owntracks
spec:
  type: ClusterIP
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
    name: recorder
  selector:
    app: owntracks-recorder


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: owntracks-ui
  name: owntracks-ui
  namespace: owntracks
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: web
  selector:
    app: owntracks-ui