---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-uptime-kuma
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  storageClassName: nfs-csi
  capacity:
    storage: 850Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 192.168.1.3/appdata/vol/uptime-kuma
    volumeAttributes:
      server: 192.168.1.3
      share: /appdata/vol/uptime-kuma

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: uptime-kuma
  name: nfs-uptime-kuma
  namespace: uptime-kuma
spec:
  storageClassName: nfs-csi
  volumeName: nfs-uptime-kuma
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 850Mi
