global:
  storageClass: local-path
namespaceOverride: mariadb
fullnameOverride: mariadb
image:
  registry: docker.io
  repository: bitnamilegacy/mariadb-galera
  tag: 12.0.2
  pullPolicy: IfNotPresent
podLabels:
  mariadb-client: "true"
existingSecret: mariadb-passwords 
rootUser:
  user: root
mariabackup:
  user: mariabackup
priorityClassName: high-priority
commonLabels:
  app.kubernetes.io/component: database
networkPolicy:
  enabled: true
  allowExternal: true
  allowExternalEgress: false
  extraIngress:
  - from:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            mariadb-client: "true"
    ports:
      - port: 3306
  - from:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            tailscale.com/parent-resource: mariadb
    ports:
      - port: 3306
  - from:
    - ipBlock:
        cidr: 192.168.1.0/27
    ports:
      - port: 3306
  extraEgress:
  - to:
    - ipBlock:
        cidr: 192.168.1.3/32
    ports:
      - port: 3306
  - to:
      - ipBlock:
          cidr: 0.0.0.0/0
    ports:
      - port: 3306
  - to:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            app.kubernetes.io/name: mariadb
    ports:
      - port: 3306
resources:
  requests:
    cpu: 25m
    memory: 1200Mi
  limits:
    # cpu: 1000m
    memory: 4000Mi
service:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  annotations:
    lbipam.cilium.io/ips: 192.168.10.10
    
    tailscale.com/expose: "true"
    tailscale.com/hostname: "home-mariadb"
    tailscale.com/proxy-class: "default"

extraEnvVars:
- name: TZ
  value: "America/Toronto"

mariadbConfiguration: |-
  [client]
  port=3306
  socket=/opt/bitnami/mariadb/tmp/mysql.sock
  plugin_dir=/opt/bitnami/mariadb/plugin

  [mysqld]
  default_storage_engine=InnoDB
  basedir=/opt/bitnami/mariadb
  datadir=/bitnami/mariadb/data
  plugin_dir=/opt/bitnami/mariadb/plugin
  tmpdir=/opt/bitnami/mariadb/tmp
  socket=/opt/bitnami/mariadb/tmp/mysql.sock
  pid_file=/opt/bitnami/mariadb/tmp/mysqld.pid
  bind_address=0.0.0.0

  ## Character set
  ##
  collation_server=utf8mb4_unicode_ci
  init_connect='SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci'
  character_set_server=utf8mb4

  ## MyISAM
  ##
  key_buffer_size=32M
  myisam_recover_options=FORCE,BACKUP

  ## Safety
  ##
  skip_host_cache
  skip_name_resolve
  max_allowed_packet=16M
  max_connect_errors=1000000
  sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY
  sysdate_is_now=1

  ## Binary Logging
  ##
  log_bin=mysql-bin
  expire_logs_days=14
  # Disabling for performance per http://severalnines.com/blog/9-tips-going-production-galera-cluster-mysql
  sync_binlog=0
  # Required for Galera
  binlog_format=row

  ## Replication to secondary server
  ##
  wsrep_gtid_mode      = on
  wsrep_gtid_domain_id = 0
  server-id            = 01
  log_slave_updates    = on
  gtid_domain_id       = 0

  ## Caches and Limits
  ##
  tmp_table_size=32M
  max_heap_table_size=32M
  # Re-enabling as now works with Maria 10.1.2
  query_cache_type=1
  query_cache_limit=4M
  query_cache_size=256M
  max_connections=500
  thread_cache_size=50
  open_files_limit=65535
  table_definition_cache=4096
  table_open_cache=4096

  ## InnoDB
  ##
  innodb=FORCE
  innodb_strict_mode=1
  # Mandatory per https://github.com/codership/documentation/issues/25
  innodb_autoinc_lock_mode=2
  # Per https://www.percona.com/blog/2006/08/04/innodb-double-write/
  innodb_doublewrite=1
  innodb_flush_method=O_DIRECT
  innodb_log_files_in_group=2
  innodb_log_file_size=128M
  innodb_flush_log_at_trx_commit=1
  innodb_file_per_table=1
  # 80% Memory is default reco.
  # Need to re-evaluate when DB size grows
  innodb_buffer_pool_size=2G
  innodb_file_format=Barracuda

  ## Logging
  ##
  log_error=/opt/bitnami/mariadb/logs/mysqld.log
  slow_query_log_file=/opt/bitnami/mariadb/logs/mysqld.log
  log_queries_not_using_indexes=1
  slow_query_log=1

  ## SSL
  ## Use extraVolumes and extraVolumeMounts to mount /certs filesystem
  # ssl_ca=/certs/ca.pem
  # ssl_cert=/certs/server-cert.pem
  # ssl_key=/certs/server-key.pem

  [galera]
  wsrep_on=ON
  wsrep_provider=/opt/bitnami/mariadb/lib/libgalera_smm.so
  wsrep_sst_method=mariabackup
  wsrep_slave_threads=4
  wsrep_cluster_address=gcomm://
  wsrep_cluster_name=galera
  wsrep_sst_auth="root:"
  # Enabled for performance per https://mariadb.com/kb/en/innodb-system-variables/#innodb_flush_log_at_trx_commit
  innodb_flush_log_at_trx_commit=2
  # MYISAM REPLICATION SUPPORT #
  wsrep_mode=REPLICATE_MYISAM

  [mariadb]
  plugin_load_add=auth_pam

extraVolumes:
- name: nfs-mariadb-backup
  persistentVolumeClaim:
    claimName: nfs-mariadb-backup
extraVolumeMounts:
- name: nfs-mariadb-backup
  mountPath: /backup
  readOnly: false

# initdbScripts:
#   initial_bootstrap.sh: |
#     #!/bin/sh
#     if [[ $(hostname) == *-0  ]]; then
#       echo "First node"
#       NEWEST_SQL_FILE=$(ls -t /backup/*.sql 2>/dev/null | head -n 1)
#       echo "$(date +%F_%T) Restoring MariaDB databases from $NEWEST_SQL_FILE..."
#       mariadb -h mariadb -u root -p$MARIADB_ROOT_PASSWORD < $NEWEST_SQL_FILE
#       echo "$(date +%F_%T) MariaDB databases have been restored"
#       echo "$(date +%F_%T) Restoring procedures..."
#       mariadb -h mariadb -u root -p$MARIADB_ROOT_PASSWORD -e /backup/mariadb-procedures.sql
#       echo "$(date +%F_%T) Restoring users..."
#       mariadb -h mariadb -u root -p$MARIADB_ROOT_PASSWORD < /backup/mariadb-users.sql
#       echo "$(date +%F_%T) Finished!"
#     else
#       echo "Not first node. Exiting script."
#     fi