apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: plex
  namespace: media
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: plex
  ingress:
    - fromEntities:
        - ingress
        - remote-node
        - world
      toPorts:
        - ports:
            - port: "32400"
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: cloudflare-tunnel
      toPorts:
        - ports:
            - port: "32400"
    - fromCIDRSet:
        - cidr: 0.0.0.0/0
      toPorts:
        - ports:
            - port: "32400"
        - ports:
            - port: "32410"
        - ports:
            - port: "32412"
        - ports:
            - port: "32413"
        - ports:
            - port: "32414"
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: ersatztv
      toPorts:
        - ports:
            - port: "32400"
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: tautulli
      toPorts:
        - ports:
            - port: "32400"
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: radarr
      toPorts:
        - ports:
            - port: "32400"
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: sonarr
      toPorts:
        - ports:
            - port: "32400"
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: maintainerr
      toPorts:
        - ports:
            - port: "32400"
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: overseerr
      toPorts:
        - ports:
            - port: "32400"
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: ersatztv
      toPorts:
        - ports:
            - port: "8409"
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
            - port: "1900"