apiVersion: v1
kind: Service
metadata:
  annotations:
    lbipam.cilium.io/ips: 192.168.10.11
    external-dns.alpha.kubernetes.io/hostname: plex-service.ucdialplans.com
  labels:
    app: plex
  name: plex-external-service
  namespace: media
spec:
  externalTrafficPolicy: Local
  ports:
    - appProtocol: http
      name: plex-web
      port: 32400
      protocol: TCP
      targetPort: http
    - name: relay
      port: 32499
      protocol: TCP
      targetPort: null
    - name: plex-companion
      port: 3005
      protocol: TCP
      targetPort: null
    - name: gdm-32410
      port: 32410
      protocol: UDP
      targetPort: null
    - name: gdm-32412
      port: 32412
      protocol: UDP
      targetPort: null
    - name: gdm-32413
      port: 32413
      protocol: UDP
      targetPort: null
    - name: gdm-32414
      port: 32414
      protocol: UDP
      targetPort: null
  selector:
    app: plex
  type: LoadBalancer