image:
  # repository: plexinc/pms-docker
  # tag: latest
  # registry: docker.io
  repository: home-operations/plex
  tag: 1.43.0.10467
  registry: ghcr.io
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 0
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
env:
- name: HOSTNAME
  value: plex.ucdialplans.com
- name: ADVERTISE_IP
  value: "http://192.168.10.11:32400/"
- name: PLEX_UID
  value: "1000"
- name: PLEX_GID
  value: "0"           
- name: TZ
  value: "America/Toronto"
- name: PLEX_CLAIM
  valueFrom:
    secretKeyRef:
      name: plex-claim-token
      key: plex-claim-token
resources:
  requests:
    cpu: 10m
    memory: 1250Mi
    gpu.intel.com/i915: "1"
  limits:
    # cpu: 2500m
    memory: 2.8Gi
    gpu.intel.com/i915: "1"
service:
  port: 32400
livenessProbe:
  httpGet:
    path: /identity
    port: http
  initialDelaySeconds: 15
  periodSeconds: 120
startupProbe:
  httpGet:
    path: /identity
    scheme: HTTPS
    port: 32400
  failureThreshold: 90
  periodSeconds: 15

persistentVolume:
  type: longhorn
  size: 40Gi
media:
  enabled: true
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: intel.feature.node.kubernetes.io/gpu
          operator: In
          values:
          - "true"
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nuc5
          - nuc6