apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 9.2.0
  releaseName: argocd
  namespace: argocd
  valuesFile: ../../base/values.yaml
  additionalValuesFiles:
  - values.yaml
  valuesMerge: merge
resources:
- ../../base
- argocd-appsets.yaml
- argocd.yaml
- external-secrets.yaml
- httproute.yaml
patches:
- path: configmap-patch.yaml
  target:
    group: ""
    version: v1
    kind: ConfigMap
    name: argocd-cm

