image:
  repository: dispatcharr/dispatcharr
  tag: 0.12.0
  registry: ghcr.io
securityContext:
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 1000
  runAsGroup: 100
#   seccompProfile:
#     type: RuntimeDefault
#   capabilities:
#     drop: ["ALL"]
envFrom:
- configMapRef:
    name: dispatcharr-env
- secretRef:
    name: dispatcharr-secrets
resources:
  requests:
    cpu: 3m
    memory: 220Mi
    gpu.intel.com/i915: "1"
  limits:
    # cpu: 1000m
    memory: 700Mi
    gpu.intel.com/i915: "1"
service:
  port: 9191
persistentVolume:
  type: longhorn
  size: 450Mi
  mountPath: /data
