image:
  repository: dispatcharr/dispatcharr
  tag: 0.12.0
  registry: ghcr.io
# securityContext:
#   allowPrivilegeEscalation: false
#   readOnlyRootFilesystem: false
#   runAsNonRoot: true
#   runAsUser: 1000
#   runAsGroup: 1000
#   seccompProfile:
#     type: RuntimeDefault
#   capabilities:
#     drop: ["ALL"]
envFrom:
- configMapRef:
    name: dispatcharr-env
- secretRef:
    name: dispatcharr-secrets
resources:
  requests:
    cpu: 3m
    memory: 220Mi
  limits:
    # cpu: 1000m
    memory: 700Mi
service:
  port: 9191
