apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../../../helm
helmCharts:
- name: baseline
  releaseName: transmission
  namespace: media
  valuesFile: values.yaml
resources:
# - networkpolicy.yaml
- service.yaml