image:
  repository: home-operations/transmission
  tag: 4.0.6
  registry: ghcr.io
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 0
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
resources:
  requests:
    cpu: 2m
    memory: 35Mi
  limits:
    # cpu: 100m
    memory: 400Mi
service:
  port: 9091
livenessProbe:
  httpGet:
    path: /transmission/web
    port: http
  initialDelaySeconds: 15
  periodSeconds: 60
  timeoutSeconds: 5
persistentVolume:
  type: nfs
  size: 2Gi
backup:
  location: cloudflare
  schedule: "35 6 * * *"  # 6:35am every day
  retain:
    hourly: 0
    daily: 3
    weekly: 0
    monthly: 0
    yearly: 0
# media:
#   enabled: true
extraVolumeMounts:
- name: media-downloads
  mountPath: /downloads
extraVolumes:
- name: media-downloads
  persistentVolumeClaim: 
    claimName: nfs-media-downloads
oidc:
  enabled: false
  secretName: env-secrets-transmission