apiVersion: v1
kind: ConfigMap
metadata:
  name: env-vars
  namespace: dmh
data:
  DMH_CONFIG_FILE: "/data/config.yaml"
  DMH_COMPONENTS: "vault,dmh"
  DMH_VAULT__FILE: "/data/vault.json"
  DMH_STATE__FILE: "/data/state.json"
  DMH_REMOTE_VAULT__URL: "http://127.0.0.1:8080"
  DMH_ACTION__PROCESS_UNIT: "hour"
  DMH_EXECUTE__PLUGIN__MAIL__SERVER: "mail.smtp2go.com"
  DMH_EXECUTE__PLUGIN__MAIL__FROM: "dmh@ucdialplans.com"
  DMH_EXECUTE__PLUGIN__MAIL__TLS_POLICY: "tls_mandatory"