apiVersion: v1
kind: ConfigMap
metadata:
  name: ucdialplans-nginx
  namespace: ucdialplans
  labels:
    app: ucdialplans
    argocd.argoproj.io/instance: ucdialplans
data:
  default: |
    server {
      root /var/www;
      listen 8080;
      add_header X-Frame-Options "SAMEORIGIN";
      add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";
      add_header Content-Security-Policy "default-src 'none'; connect-src 'self' cloudflareinsights.com; script-src 'self' https://apis.live.net https://js.live.net https://code.jquery.com https://maxcdn.bootstrapcdn.com https://cdn.jsdelivr.net/npm/handsontable@12.1.3/dist/ https://unpkg.com/scrollreveal@4.0.0/dist/ static.cloudflareinsights.com ajax.cloudflare.com https://cdnjs.buymeacoffee.com; style-src 'self' 'unsafe-inline' https://maxcdn.bootstrapcdn.com https://cdn.jsdelivr.net/npm/handsontable@12.1.3/dist/; font-src 'self' https://fonts.gstatic.com https://maxcdn.bootstrapcdn.com; img-src 'self' https://js.live.net https://www.paypal.com https://www.paypalobjects.com https://cdnjs.buymeacoffee.com; frame-src 'self' https://login.live.com; frame-ancestors 'self'; form-action 'self' https://www.paypal.com; base-uri 'self'; object-src 'none'; media-src 'none'";
      add_header X-XSS-Protection "1; mode=block";
      add_header X-Content-Type-Options nosniff;
      add_header Referrer-Policy "strict-origin";
      add_header Permissions-Policy "accelerometer=(), autoplay=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), fullscreen=(self), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(self), usb=(), web-share=(), xr-spatial-tracking=()";

      location / {
        limit_except GET HEAD POST { deny all; }
        fastcgi_index default.cshtml;
        fastcgi_pass 127.0.0.1:9000;
        include /etc/nginx/fastcgi_params;
      }

            location /api {
        limit_except GET HEAD { deny all; }
        fastcgi_index process.aspx;
        fastcgi_pass 127.0.0.1:9000;
        include /etc/nginx/fastcgi_params;
            }

            location /queryapi {
        limit_except GET HEAD { deny all; }
        fastcgi_index process.aspx;
        fastcgi_pass 127.0.0.1:9000;
        include /etc/nginx/fastcgi_params;
            }

            location /regexrangeapi {
        limit_except GET HEAD { deny all; }
        fastcgi_index process.aspx;
        fastcgi_pass 127.0.0.1:9000;
        include /etc/nginx/fastcgi_params;
            }

            location /rnlapi {
        limit_except GET HEAD { deny all; }
        fastcgi_index process.aspx;
        fastcgi_pass 127.0.0.1:9000;
        include /etc/nginx/fastcgi_params;
            }

            location /healthcheck {
        limit_except GET HEAD { deny all; }
        fastcgi_index process.aspx;
        fastcgi_pass 127.0.0.1:9000;
        include /etc/nginx/fastcgi_params;
            }
    }
