apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: ollama
  repo: https://helm.otwld.com/
  version: 1.45.0
  releaseName: ollama
  namespace: ollama
  valuesFile: values-ollama.yaml
- name: open-webui
  repo: https://helm.openwebui.com/
  version: 12.5.0
  releaseName: open-webui
  valuesFile: values-openwebui.yaml
resources:
- namespace.yaml
- volume.yaml