apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: nextcloud
helmCharts:
- name: ollama
  repo: https://helm.otwld.com/
  version: 1.43.0
  releaseName: ollama
  namespace: ollama
  valuesFile: values.yaml
resources:
- namespace.yaml
- volume.yaml