apiVersion: v1
kind: ConfigMap
metadata:
  name: env-vars
  namespace: paperless
data:
  PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
  PAPERLESS_CONSUMER_DISABLE: "true"
  PAPERLESS_DBENGINE: postgresql
  PAPERLESS_DBHOST: home-rw.cnpg.svc.cluster.local
  PAPERLESS_DBPORT: "5432"
  PAPERLESS_URL: "https://paperless.ucdialplans.com"
  USERMAP_UID: "1000"
  USERMAP_GID: "1000"
  TZ: "America/Toronto"