---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: env-secrets
  namespace: paperless
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: env-secrets
    template:
      engineVersion: v2
      data:
        PAPERLESS_DBUSER: "{{ .dbUsername }}"
        PAPERLESS_DBPASS: "{{ .dbPassword }}"
        PAPERLESS_REDIS: "redis://:{{ .redisPassword }}@redis-service.redis.svc.cluster.local:6379"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: "{{ .providers }}"
  data:
  - secretKey: dbUsername
    remoteRef:
      key: /database/paperless
      property: username
  - secretKey: dbPassword
    remoteRef:
      key: /database/paperless
      property: password
  - secretKey: redisPassword
    remoteRef:
      key: /redis
      property: password
  - secretKey: providers
    remoteRef:
      key: /paperless
      property: PAPERLESS_SOCIALACCOUNT_PROVIDERS