image:
  repository: paperless-ngx/paperless-ngx
  tag: 2.20.1
  registry: ghcr.io
priorityClassName: low-priority
extraLabels:
  cnpg-client: "true"
securityContext:
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 1000
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
    add:
    - "CHOWN"
    - "SETGID"
    - "SETUID"
    - "DAC_OVERRIDE"
env:
- name: TZ
  value: "America/Toronto"
resources:
  requests:
    cpu: 10m
    memory: 450Mi
  limits:
    # cpu: 200m
    memory: 800Mi
service:
  port: 8000
envFrom:
- configMapRef:
    name: env-vars
- secretRef:
    name: env-secrets
persistentVolume:
  type: nfs
  size: 20Gi
  mountPath: /paperless
extraVolumeMounts:
- name: paperless-config
  mountPath: /usr/src/paperless/data
  subPath: data
- name: paperless-config
  mountPath: /usr/src/paperless/media
  subPath: media
backup:
  location: cloudflare
  schedule: "50 06 * * *"