apiVersion: v1
kind: ConfigMap
metadata:
  name: env-vars-backend
  namespace: monize
data:
  NODE_ENV: "production"
  DATABASE_HOST: "monize-rw.cnpg.svc.cluster.local"
  DATABASE_NAME: monize
  PUBLIC_APP_URL: https://monize-demo.ucdialplans.com
  LOCAL_AUTH_ENABLED: "true"
  REGISTRATION_ENABLED: "false"
  DEMO_MODE: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-vars-frontend
  namespace: monize
data:
  NODE_ENV: "production"
  INTERNAL_API_URL: http://monize-backend-service:3001
  PUBLIC_APP_URL: https://monize-demo.ucdialplans.com
