apiVersion: v1
kind: ConfigMap
metadata:
  name: env-vars-backend
  namespace: monize
data:
  NODE_ENV: "production"
  DATABASE_HOST: "monize-rw.cnpg.svc.cluster.local"
  DATABASE_NAME: monize
  PUBLIC_APP_URL: https://monize-demo.ucdialplans.com
  OIDC_ISSUER_URL: https://auth.ucdialplans.com
  OIDC_CALLBACK_URL: https://monize.ucdialplans.com/api/v1/auth/oidc/callback
  LOCAL_AUTH_ENABLED: "true"
  REGISTRATION_ENABLED: "true"
  SMTP_HOST: "mail.smtp2go.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"  # Not required for STARTTLS
  EMAIL_FROM: "monize@ucdialplans.com"
  DEMO_MODE: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-vars-frontend
  namespace: monize
data:
  NODE_ENV: "production"
  INTERNAL_API_URL: http://monize-backend-service:3001
  PUBLIC_APP_URL: https://monize-demo.ucdialplans.com
