# This file overrides some ArgoCD ApplicationSet parameters. It does not have to be populated, but it must exist.
autoSync: true
info:
- name: "Website:"
  value: "https://nextcloud.com"
- name: "Documentation:"
  value: "https://docs.nextcloud.com/server/latest/admin_manual/"
- name: "Repository:"
  value: "https://github.com/nextcloud"