apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../../../helm
helmCharts:
- name: baseline
  releaseName: radarr
  namespace: media
  valuesFile: values.yaml
resources:
- database.yaml
# - networkpolicy.yaml