image:
  repository: 11notes/radarr
  tag: 6.0.4
  registry: ghcr.io
extraLabels:
  appGroup: media-arr
envFrom:
  secretRef:
    secretName: env-secrets-radarr
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 0
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
resources:
  requests:
    cpu: 2m
    memory: 200Mi
  limits:
    # cpu: 1000m
    memory: 750Mi
service:
  port: 7878
livenessProbe:
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 20
  timeoutSeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 10
media:
  enabled: true
persistentVolume:
  type: nfs
  size: 2.5Gi
  mountPath: /radarr/etc
extraVolumes:
- name: tmpfs
  emptyDir:
    medium: Memory
extraVolumeMounts:
- name: tmpfs
  mountPath: /tmp
backup:
  location: cloudflare
  schedule: "00 07 * * *"
oidc:
  enabled: true
  secretName: env-secrets-radarr