apiVersion: v1
kind: ConfigMap
metadata:
  name: env-vars-backend
  namespace: moneymate
data:
  NODE_ENV: "production"
  DATABASE_HOST: "home-rw.cnpg.svc.cluster.local"
  DATABASE_NAME: moneymate
  PUBLIC_APP_URL: https://moneymate.ucdialplans.com
  OIDC_ISSUER_URL: https://auth.ucdialplans.com
  OIDC_CALLBACK_URL: https://moneymate.ucdialplans.com/api/v1/auth/oidc/callback
  LOCAL_AUTH_ENABLED: true
  REGISTRATION_ENABLED: false

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-vars-frontend
  namespace: moneymate
data:
  NODE_ENV: "production"
  INTERNAL_API_URL: http://moneymate-backend-service:3001
  PUBLIC_APP_URL: https://moneymate.ucdialplans.com
