---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: env-secrets
  namespace: moneymate
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: env-secrets
  data:
  - secretKey: DATABASE_USER
    remoteRef:
      key: /database/moneymate
      property: username
  - secretKey: DATABASE_PASSWORD
    remoteRef:
      key: /database/moneymate
      property: password
  - secretKey: JWT_SECRET
    remoteRef:
      key: /moneymate
      property: JWT_SECRET
  - secretKey: OIDC_CLIENT_ID
    remoteRef:
      key: /moneymate
      property: OIDC_CLIENT_ID
  - secretKey: OIDC_CLIENT_SECRET
    remoteRef:
      key: /moneymate
      property: OIDC_CLIENT_SECRET
  - secretKey: SMTP_USER
    remoteRef:
      key: /email/smtp2go
      property: username
  - secretKey: SMTP_PASSWORD
    remoteRef:
      key: /email/smtp2go
      property: password