apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../../../helm
helmCharts:
- name: baseline
  releaseName: moneymate
  namespace: moneymate
  valuesFile: values-backend.yaml
- name: baseline
  releaseName: moneymate
  namespace: moneymate
  valuesFile: values-frontend.yaml
resources:
- database.yaml
- env-vars.yaml
- external-secrets.yaml
- namespace.yaml
