---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: calibre-downloader-aa
spec:
  serviceName: calibre-downloader-aa
  replicas: 1
  revisionHistoryLimit: 2
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: calibre-downloader-aa
  template:
    metadata:
      labels:
        app: calibre-downloader-aa
        name: calibre-downloader-aa
        appGroup: media-arr
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      automountServiceAccountToken: false
      priorityClassName: medium-priority
      containers:
      - name: calibre-downloader-aa
        image: ghcr.io/calibrain/shelfmark:v1.0.0
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          # runAsUser: 1000
          # runAsGroup: 0
          seccompProfile:
            type: RuntimeDefault
          # capabilities:
          #   drop: ["ALL"]
          #   add:
          #   - "CHOWN"
          #   - "SETGID"
          #   - "SETUID"
          #   - "DAC_OVERRIDE"
          #   - "DAC_READ_SEARCH"
          #   - "NET_ADMIN"
          #   - "NET_RAW"
        env:
        - name: CLOUDFLARE_PROXY_URL
          value: http://cloudflare-bypass-service:8000
        - name: PUID
          value: "1000"
        - name: PGID
          value: "0"
        - name: TZ
          value: "America/Toronto"
        resources:
          requests:
            cpu: 1m
            memory: 60Mi
          limits:
            # cpu: 1000m
            memory: 750Mi
        ports:
        - containerPort: 8084
          name: http-dl-aa
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http-dl-aa
          initialDelaySeconds: 15
          periodSeconds: 60
          timeoutSeconds: 5
        volumeMounts:
        - name: books-to-import
          mountPath: /cwa-book-ingest
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      volumes:
      - name: books-to-import
        persistentVolumeClaim:
          claimName: nfs-books-to-import