---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cloudflare-bypass
spec:
  serviceName: cloudflare-bypass
  replicas: 1
  revisionHistoryLimit: 2
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: cloudflare-bypass
  template:
    metadata:
      labels:
        app: cloudflare-bypass
        name: cloudflare-bypass
        appGroup: media-arr
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      automountServiceAccountToken: false
      priorityClassName: medium-priority
      containers:
      - name: cloudflare-bypass
        image: ghcr.io/sarperavci/cloudflarebypassforscraping@sha256:4a3b6af1ba210e2a776897d0bf26f6bd84a99968e208f9c6514c0b9dbc529db6
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
          seccompProfile:
            type: RuntimeDefault
          # capabilities:
          #   drop: ["ALL"]
          #   add:
          #   - "CHOWN"
          #   - "SETGID"
          #   - "SETUID"
          #   - "DAC_OVERRIDE"
          #   - "DAC_READ_SEARCH"
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "100"
        - name: TZ
          value: "America/Toronto"
        resources:
          requests:
            cpu: 85m
            memory: 300Mi
          limits:
            # cpu: 1000m
            memory: 800Mi
        ports:
        - containerPort: 8000
          name: http-cloudflare
          protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: http-cloudflare
        #   initialDelaySeconds: 15
        #   periodSeconds: 60
        #   timeoutSeconds: 5
      dnsConfig:
        options:
          - name: ndots
            value: "1"
