---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: shelfmark
  namespace: media
spec:
  parentRefs:
  - name: tls
    namespace: cilium
    sectionName: https
  hostnames:
  - "book-dl.ucdialplans.com"
  rules:
  - backendRefs:
    - name: shelfmark-service
      namespace: media
      kind: Service
      port: 8084