apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
helmGlobals:
  chartHome: ../../../../helm
helmCharts:
- name: baseline
  releaseName: calibre
  namespace: media
  valuesFile: values.yaml
resources:
- deploy-cloudflare-bypass.yaml
- deploy-downloader-aa.yaml
- httproute.yaml
- networkpolicy.yaml
- service.yaml
- volume.yaml
