apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
helmGlobals:
  chartHome: ../../../../helm
helmCharts:
- name: baseline
  releaseName: calibre
  namespace: media
  valuesFile: values-calibre.yaml
- name: baseline
  releaseName: shelfmark
  namespace: media
  valuesFile: values-shelfmark.yaml
resources:
- external-secrets.yaml
- networkpolicy.yaml
- volume.yaml
