image:
  repository: 11notes/sonarr
  tag: 4.0.16
  registry: ghcr.io
extraLabels:
  appGroup: media-arr
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 0
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
resources:
  requests:
    cpu: 2m
    memory: 200Mi
  limits:
    # cpu: 1000m
    memory: 350Mi
service:
  port: 8989
livenessProbe:
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 20
  timeoutSeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 10
media:
  enabled: true
persistentVolume:
  type: nfs
  size: 1Gi
  mountPath: /sonarr/etc
extraVolumes:
- name: tmpfs
  emptyDir:
    medium: Memory
extraVolumeMounts:
- name: tmpfs
  mountPath: /tmp
backup:
  location: cloudflare
  schedule: "05 07 * * *"
oidc:
  enabled: true
  secretName: env-secrets-sonarr