# This file overrides some ArgoCD ApplicationSet parameters. It does not have to be populated, but it must exist.
autoSync: false
info:
- name: "Website:"
  value: "https://www.portainer.io/"
- name: "Documentation:"
  value: "https://docs.portainer.io/"
- name: "Repository:"
  value: "https://github.com/portainer/portainer"