---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-password-insight
  namespace: redis
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: redis-password-insight
  data:
  - secretKey: RI_REDIS_PASSWORD
    remoteRef:
      key: /redis
      property: password