---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: neuvector
  namespace: neuvector
spec:
  parentRefs:
  - name: tls
    namespace: cilium
    sectionName: https
  hostnames:
  - "neuvector.ucdialplans.com"
  rules:
  - backendRefs:
    - name: neuvector-service-webui
      namespace: neuvector
      kind: Service
      port: 8443