apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
helmCharts:
- name: loki
  repo: https://grafana.github.io/helm-charts
  version: 6.49.0
  releaseName: loki-promtail
  namespace: monitoring
  valuesFile: ../../base/values-loki.yaml
  additionalValuesFiles:
  - values-loki.yaml
  valuesMerge: merge
# - name: promtail
#   repo: https://grafana.github.io/helm-charts
#   version: 6.17.1
#   releaseName: loki-promtail
#   namespace: monitoring
#   valuesFile: ../../base/values-promtail.yaml
resources:
- ../../base