apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: reloader
  repo: https://stakater.github.io/stakater-charts
  version: 2.2.4
  releaseName: reloader
  namespace: reloader
  valuesFile: values.yaml
resources:
- namespace.yaml