image:
  repository: 11notes/sabnzbd
  tag: 4.5.5
  registry: ghcr.io
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 0
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
resources:
  requests:
    cpu: 2m
    memory: 100Mi
  limits:
    # cpu: 1000m
    memory: 2.0Gi  # Don't go below this. Even though it looks like its not using memory, the pod will get OOMKilled as soon as there's any load.
service:
  port: 8080
persistentVolume:
  type: longhorn
  size: 300Mi
  mountPath: /sabnzbd/etc
extraVolumeMounts:
- name: media-downloads
  mountPath: /downloads
- name: tmpfs
  mountPath: /tmp
extraVolumes:
- name: media-downloads
  persistentVolumeClaim: 
    claimName: nfs-media-downloads
- name: tmpfs
  emptyDir:
    medium: Memory
# oidc:
#   enabled: true
#   secretName: env-secrets-sabnzbd
