apiVersion: v1
kind: Service
metadata:
  labels:
    app: esphome-service
  name: esphome-service
  namespace: homeassist
spec:
  type: ClusterIP
  ports:
  - port: 6052
    protocol: TCP
    targetPort: http
    name: web
  selector:
    app: esphome