---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-esphome
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  storageClassName: nfs-csi
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 192.168.1.3/appdata/vol/esphome
    volumeAttributes:
      server: 192.168.1.3
      share: /appdata/vol/esphome

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-esphome
  namespace: homeassist
spec:
  storageClassName: nfs-csi
  volumeName: nfs-esphome
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi